voteRestController eliminated, voteService and voteRepository updated…
Gregaria-Rosario/proyecto-barrio pull request #10
Opened 2021-02-03 23:38 UTC by NahuelBullonJensen

…, WebException created

2021-02-04 17:35 UTC, pablocolaiacovo commented on src/main/java/com/gregaria/proyectobarrio/services/VoteService.java
> +  public Vote activate(Vote vote) throws WebException {
Se puede agregar un toggle también? que cambie el voto al estado opuesto directamente. Me parece que puede ser util en algún momento.

2021-02-05 15:17 UTC, NahuelBullonJensen commented on src/main/java/com/gregaria/proyectobarrio/services/VoteService.java
> +  public Vote activate(Vote vote) throws WebException {
Osea además de los otros dos un toggle?, okis, lo llamo "activeToggle" o como pensas que es mejor?

2021-02-05 15:20 UTC, pablocolaiacovo commented on src/main/java/com/gregaria/proyectobarrio/services/VoteService.java
> +  public Vote activate(Vote vote) throws WebException {
Me parece que va a ser mas simple de usar, yo haría algo asi como:

```java
public Vote toggle(Vote vote) { }
```

O capaz que directamente con el voteId, no se si hace falta pasar el voto completo para hacer esto

2021-02-12 22:16 UTC, gigilevit approved these changes

2021-03-17 21:59 UTC, gisegalaburri approved these changes

2021-03-17 22:55 UTC, gisegalaburri requested changes
Porqué eliminaste `voteRestController.java` ? 
Sería bueno conservar todos los restControllers y también tener los controllers que retornan html.

2021-03-17 23:21 UTC, gisegalaburri approved these changes

2021-03-17 23:46 UTC, merged